### ISSUE TITLE
dmxp512 in processing 3

### ISSUE THREAD

**Issue by ryanh31** [hdavid/dmxP512#3]
Hi Great library!
I am trying to run the library on processing 3. I am successful in using it in Processing 2 but I want to run it on a raspberry pi for an installation and I am using processing 3.
Is this a possibility?
I am connecting it to a Lanbox.

Thanks,
Ryan

**Comment by hdavid** [comment]
hi,

i am not sure to follow. dmxP512 is available from the processing 3 libraries.
i just had a go on a virgin computer using last processing 3. it downloaded dmxP512 just fine.

regards,

henri

**Comment by ryanh31** [comment]
fair enough, yes it downloads but when I go to run the sketch it gives an
error.
I am sure you also tried to run a sketch and did not get the error, that is
why you closed this issue. It must be me.
I have tried on two computers and still no luck.
oh well.
[image: Screen Shot 2019-12-16 at 5.31.33 PM.png]

**Comment by hdavid** [comment]
i dont have a lanbox myself to try. but with a bit of google searching i found that a method has been removed.

what you can try: 
- copy UDP.java and DmxP512.java into your sketch (as new classes).
- remove the first line: package dmxP512;
- edit UDP.java like so:
```// register this object to the PApplet, 
    // if it's used with Processing
    try {
      if ( owner instanceof PApplet ) 
        ((PApplet)owner).registerMethod("dispose", this );
        //((PApplet)owner).registerDispose( this );
    }
    catch( NoClassDefFoundError e ) {;}
```

i could not test it as i dont have a lanbox for years, but at least it compiled and ran okay it seems.

**Comment by ryanh31** [comment]
thanks i will give it a try and let you know.
i appreciate your help!
thanks
ryan

**Comment by ryanh31** [comment]
Hi David
yes it worked! t
hanks for working on this for me.
I have attached my test patch with the classes.
it is a simple test that uses the mouseX on channel 1.
Best,
Ryan

**Comment by ryanh31** [comment]
i Meant Hi Henri

sorry!
